In [1]:
import numpy as np

## Universal Functions

### Simple arithmetic function

In [2]:
a = [1,2,3,4]
b =[5,6,7,8]
print(np.add(a,b))
print(type(np.add))

[ 6  8 10 12]
<class 'numpy.ufunc'>


In [3]:
print(np.subtract(b,a))

[4 4 4 4]


In [4]:
print(np.multiply(a,b))

[ 5 12 21 32]


In [5]:
print(np.divide(b,a))

[5.         3.         2.33333333 2.        ]


In [6]:
print(np.power(a,b))

[    1    64  2187 65536]


In [7]:
print(np.mod(a,b))

[1 2 3 4]


In [8]:
print(np.remainder(a,b))

[1 2 3 4]


In [9]:
print(np.divmod(b,a))

(array([5, 3, 2, 2]), array([0, 0, 1, 0]))


In [10]:
c=[-1,-2,3,1,-4,3,-4,5]
print(np.absolute(c))

[1 2 3 1 4 3 4 5]


### Rounding functions

In [11]:
print(np.trunc([-3.4456,3.7454]))
print(np.fix([-3.4456,3.7454]))

[-3.  3.]
[-3.  3.]


In [12]:
print(np.around(3.23334,2))

3.23


In [13]:
print(np.floor([-3.5666,3.5744]))
print(np.ceil([-3.5666,3.5744]))

[-4.  3.]
[-3.  4.]


### Summation functions

In [14]:
d = np.array([1,2,3])
e = np.array([1,2,3])
print(np.sum([d,e]))
print(np.sum([d,e],axis =1))

12
[6 6]


In [15]:
##cummulative sum
print(np.cumsum(d))

[1 3 6]


### Porduct functions

In [16]:
print(np.prod([d,e]))
print(np.prod([d,e],axis=1))

36
[6 6]


In [17]:
print(np.cumprod(d))

[1 2 6]


### Difference Functions

In [18]:
arr = np.array([10,15,12,13])
print(np.diff(arr))
print(np.diff(arr,n=2))

[ 5 -3  1]
[-8  4]


### LCM functions

In [19]:
num1 = 4
num2 = 5
arr1 = np.array([3,6,9])
print(np.lcm(num1,num2))

20


In [20]:
print(np.lcm.reduce(arr1))

18


### GCD or HCF functions

In [21]:
print(np.gcd(num1,num2))

1


In [22]:
print(np.gcd.reduce(arr1))

3


### Trignometry Function

In [23]:
z = np.sin(np.pi/2)
z

1.0

In [25]:
##Convert Degrees Into Radians
## radians values are pi/180 * degree_values.
array = np.array([10,20,30,40,45])
rad = np.deg2rad(array)
rad

array([0.17453293, 0.34906585, 0.52359878, 0.6981317 , 0.78539816])

In [26]:
###Radians to Degrees
arr2 =np.array([0.17453293, 0.34906585, 0.52359878, 0.6981317 , 0.78539816])
deg = np.rad2deg(arr2)
deg

array([10.00000028, 19.99999998, 30.00000025, 39.99999995, 44.99999981])

In [31]:
## Finding Angles
print( np.arcsin(1.0))
print(np.arccos(1.0))
print(np.arctan(1.0))


1.5707963267948966
0.0
0.7853981633974483


In [32]:
##Hypotenues
base = 10
prep = 20
print(np.hypot(base,prep))

22.360679774997898


In [34]:
### Hyperbolic Functions
print(np.sinh(np.pi/2))
print(np.cosh(np.pi/2))
print(np.tanh(np.pi/2))

2.3012989023072947
2.5091784786580567
0.9171523356672744


### Set Operations

In [35]:
set = np.array([1,1,1,1,2,3,4,5,6,5,7])
print(np.unique(set))

[1 2 3 4 5 6 7]


In [40]:

set1 = np.array([1,2,3,4])
set2 =np.array([3,4,5,6,7,8])
##Finding Union
print(np.union1d(set1,set2))
##Finding Intersection
print(np.intersect1d(set1,set2,assume_unique=True))
##Finding Difference
print(np.setdiff1d(set1,set2))
###Finding Symmetric Difference
print(np.setxor1d(set1,set2))

[1 2 3 4 5 6 7 8]
[3 4]
[1 2]
[1 2 5 6 7 8]
